version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies.."
      - pip install
    build: 
      commands:
        - echo "Zipping deployments .."
        - cd lib
        - zip -r9 ../deployment_package.zip .
        - cd ..
        - zip -g deployment_package>zip lambda_function.py
    post_build:
      commands:
        - echo "Updating lambda fucntion.."
        - aws lambda update-function-code --function-name WeatherPythonApp --zip-file fileb://deployment_package.zip
        - echo DONE!!
